// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqaedtxvrejlatuttwup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxYWVkdHh2cmVqbGF0dXR0d3VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MDM2NjUsImV4cCI6MjA3MjM3OTY2NX0.139kBzThLnE6Pb_IxuvWXnX0sIKFZs_WMtWjf7FYJDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});